theme = "blowfish"
baseURL = "https://yaseen.tech"
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 20
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
