languageCode = "en"
languageName = "English"
weight = 1

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
logo = "img/yt-logo-125x125.png"

[author]
name = "Yaseen Younus, M.S."
image = "img/yaseen-black-bg.png"
email = "yaseenyounus1@gmail.com"
headline = "Cloud | DevOps | SRE | Platform | Architecture | Automation"
bio = "Personal site and tech blog"
links = [ 
    { email = "mailto:yaseenyounus1@gmail.com" }, 
    { github = "https://github.com/yaseenyounus" }, 
    { linkedin = "https://www.linkedin.com/in/yaseenyounus/" },
    { medium = "https://medium.com/@yaseenyounus" },
    { youtube = "https://www.youtube.com/@yaseenxyounus" }
]
