languageCode = "en"
languageName = "English"
weight = 1
title = "yaseen.tech"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
logo = "yt.png"
secondaryLogo = "yt.png"

[author]
name = "Yaseen Younus"
image = "yaseen-black-bg.png"
headline = """
personal site & tech blog  
Cloud | DevOps | SRE | Platform | Architecture | Automation
"""
bio = "Cloud | DevOps | SRE | Architecture | Automation"
links = [ { email = "" }, { github = "https://github.com/yaseenyounus" }, { linkedin = "https://www.linkedin.com/in/yaseenyounus/" } ]
