[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Background"
  pageRef = "/background"
  weight = 10

# [[main]]
#   name = "Certifications"
#   pageRef = "/certifications"
#   weight = 20

# [[main]]
#   name = "Publications"
#   pageRef = "/publications"
#   weight = 30

[[main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 40
