colorScheme = "forest"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "data-flow.jpg"
defaultFeaturedImage = "triangle-colors.png"
highlightCurrentMenuArea = true
smartTOC = true

[header]
layout = "basic"

[background]
layout = "page"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true
showMenu = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/blog"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "data-flow.jpg"

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
heroStyle = ""
cardView = true

[firebase]

[fathomAnalytics]

[verification]
